### ISSUE TITLE
Add interface for querying if a user with specific email address exists

### ISSUE THREAD

**Issue by EricDiao** [ShanghaitechGeekPie/oj-gitlab-middleware#5]
The current version only provides interface for adding user to GitLab, without anyway for backend to know if a user exists. This leak of interface cause some inconsistency problem between backend and gitlab (e.g., ShanghaitechGeekPie/oj-backend/issues/16). Then an interface for querying if a user with specific email address exists seems to be needed so that we cloud check if a user exists before creating it.

A proposal is to implement `GET` at `/users/<user_email>`. The interface should return any `2xx` status code (detailed user information is not an urgent so far) if the user exists and `404` if not.

**Comment by llk89** [comment]
Proposal accepted. I'll return 204 for now. I don't have much info regarding user anyway.

Above all else, just let me update the rust std first...
