### ISSUE TITLE
Unknown error report in middleware log

### ISSUE THREAD

**Issue by ZoneLikeWonderland** [ShanghaitechGeekPie/oj-gitlab-middleware#6]
When I am trying to create a new course, the middleware shows that
![图片](https://user-images.githubusercontent.com/41963972/68927025-cbf2f000-07c1-11ea-8f8b-59ebe50aee7d.png)
What happened?

**Comment by EricDiao** [comment]
It seems the creation of user in GitLab server caused some kind of anomly in the databases which results in that creation of user is successful in GitLab but not successful in the middleware database (just a guess).

**Comment by llk89** [comment]
This should have been resolved in 010799a2d91f32de4551e2cbd461c938693ee6b3
